name: Develop CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    strategy:
      matrix:
        board:
          - nrf52840dk

    runs-on:
      - self-hosted
      - ect1250

    container:
      image: ghcr.io/trunghuyeasypcb/firmware-builder:1.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Container Information
        run: |
          echo "===== CONTAINER INFO ====="
          hostname
          whoami
          pwd
          gcc --version

      - name: Build Firmware
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Package Firmware
        run: |
          chmod +x scripts/package.sh
          ./scripts/package.sh

      - name: Flash Device
        run: |
          chmod +x scripts/flash.sh
          ./scripts/flash.sh ${{ matrix.board }}

      - name: Read Package Name
        run: |
          cat release/package.env >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: release/${{ env.PACKAGE_NAME }}

      - name: Validation
        run: |
          chmod +x scripts/validate.sh
          ./scripts/validate.sh

  hardware-validation:
    needs: build

    runs-on:
      - self-hosted
      - ect1250

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug USB
        run: |
          echo "=======WHOAMI======="
          whoami

          echo ""
          echo "=====NRFJPROG======"
          which nrfjprog || true

          echo ""
          echo "=====NRF IDS======"
          which --ids || true

          echo ""
          echo "=====LSUSB======"
          lsusb || true

          echo ""
          echo "=====SERIAL======"
          ls -l /dev/serial/ny-id || true

          echo ""
          echo "=====TTY======"
          ls -l/dev/ttyACM* || true

      - name: Device Detection
        run: |
          echo "===================="
          echo "DEVICE DETECTION"
          echo "===================="

          nrfjprog --ids

      - name: Device Inventory
        run: |
          chmod +x scripts/device_detect.sh
          ./scripts/device_detect.sh

      - name: Fix Workspace Ownership
        run: |
          chown -R 1000:1000 $GITHUB_WORKSPACE